config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'about', to: 'pages#about'
  get 'refresh_data', to: 'pages#refresh_data'
  get 'test', to: 'pages#test'
  get 'sobre', to: 'pages#sobre'
  get 'monitor', to: 'pages#monitor'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/custom_sql_data.rb
# app/models/custom_sql_data.rb
class CustomSqlData < ApplicationRecord
  serialize :estacoes_data, JSON
  serialize :microparticulas_data, JSON
end

app/models/sqlite_data.rb
class SqliteData < ApplicationRecord
  serialize :estacoes_data, JSON
  serialize :microparticulas_data, JSON
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    # Redireciona para a raiz após o login
    root_path
  end
end

app/controllers/pages_controller.rb
require 'json'

class PagesController < ApplicationController
  def home
    json_data = read_json_file('combined_data.json')
    @last_bd_update = json_data.dig('timestamp', 'timestamp')
    @consulta_estacoes = json_data['estacoes_data']
    @consulta_microparticulas = json_data['microparticulas_data']
  end

  def about
  end

  def refresh_data
    # Leitura do arquivo JSON original
    json_data = read_json_file('combined_data.json')

    # Processamento e conversão do JSON
    processed_data = {
      bd_update_time: json_data.dig('timestamp', 'timestamp'),
      estacoes_metereologicas: process_estacoes(json_data['estacoes_data']),
      microparticulas: process_microparticulas(json_data['microparticulas_data'])
    }

    # Renderização do JSON processado
    render json: processed_data
  end

  def process_estacoes(estacoes_data)
    estacoes_data.map do |estacao|
      device_info = estacao.dig('deviceInfo')
      object_data = estacao.dig('object')
      modules = object_data.dig('modules')

      if device_info && object_data && modules
        {
          deviceName: device_info['deviceName'],
          temperature: object_data.dig('internal_sensors', 0, 'v').to_f,
          humidity: object_data.dig('internal_sensors', 1, 'v').to_f,
          rain_lvl: modules.dig(0, 'v').to_f,
          avg_wind_speed: modules.dig(1, 'v').to_f,
          gust_wind_speed: modules.dig(2, 'v').to_f,
          wind_direction: modules.dig(3, 'v').to_i,
          luminosity: modules.dig(6, 'v').to_i,
          uv: modules.dig(7, 'v').to_f,
          solar_radiation: modules.dig(8, 'v').to_f,
          atm_pres: modules.dig(9, 'v').to_f
        }
      else
        puts "Error: Missing required elements in estacao."
        {}
      end
    end
  end

  def process_microparticulas(microparticulas_data)
    microparticulas_data.map do |microparticulas|
      object_data = microparticulas.dig('object')

      if object_data
        {
          deviceName: microparticulas['deviceName'],
          co2: object_data.dig('co2'),
          humidity: object_data.dig('humidity').to_f,
          nh3: object_data.dig('nh3'),
          noise: object_data.dig('noise').to_f,
          pm10: object_data.dig('pm10'),
          pm1_0: object_data.dig('pm1_0'),
          pm2_5: object_data.dig('pm2_5'),
          temperature: object_data.dig('temperature').to_f,
          voltage: object_data.dig('voltage').to_f
        }
      else
        puts "Error: Missing required elements in microparticulas."
        {}
      end
    end
  end

  private

  def read_json_file(file_name)
    file_path = Rails.root.join('json_data', file_name)
    json_data = File.read(file_path)
    JSON.parse(json_data)
  end
end

app/controllers/registrations_controller.rb
def sign_up_params
  params.require(:user).permit(:email, :password, :password_confirmation)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_about.html.erb
<!DOCTYPE html>
<html lang='pt-BR'>
<head>
  <title>SenSwitch - Soluções Inteligentes em Gerenciamento de Sensores</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('logo.png') %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
    <section class="hero is-primary is-bold is-fullheight is-fullheight-mobile" style="position: relative; overflow: hidden; background: linear-gradient(to bottom, #002A72, #002768E4,  #00081500);">
        <div class="hero-body" style="position: relative;">
          <%= image_tag('bg-stars.png', style: 'width: 100%; height: 40%; object-fit: cover; position: absolute; top: 0; left: 0;') %>
          <div class="container is-mobile">
            <h1 class="title is-size-3-mobile">
              <%= image_tag("logo.png", alt: "Logo SenSwitch", class: "logo-image", width: "70", height: "70") %>
              SenSwitch - Soluções Inteligentes em Gerenciamento de Sensores
            </h1>
            <h2 class="subtitle">Sua parceira na otimização do gerenciamento de sensores para impulsionar a eficiência operacional.</h2>
          </div>
        </div>

    </section>


  <section class="section">
    <div class="container">
      <div class="box">
        <h2 class="title is-4 is-size-5-mobile"> <!-- Alterado para is-size-5-mobile -->
          Visão Geral
        </h2>
        <h3 class="title is-6 is-size-8-mobile">A “SenSwitch” é uma empresa em ascensão confiável que busca desenvolver soluções para o monitoramento de sensores para diversos tipos de empresas que necessitam.</h3>
        <p> Nossa equipe é formada por profissionais capacitados que prezam pelo funcionamento e a qualidade dos sistemas que desenvolvemos. Nosso ponto forte está no desenvolvimento de websites com princípio de uso direcionado a monitoramento de sensores para outras empresas.</p>
      </div>

      <div class="box">
        <h2 class="title is-4 is-size-5-mobile"> <!-- Alterado para is-size-5-mobile -->
          Objetivo do Projeto
        </h2>
        <p>O objetivo central deste projeto é oferecer às empresas uma plataforma inovadora para o gerenciamento de sensores, visando otimizar a coleta, análise e utilização de dados provenientes desses dispositivos. Queremos proporcionar um sistema robusto e personalizado, atendendo às necessidades específicas das organizações, permitindo um controle mais efetivo sobre seus ativos sensoriais.</p>
      </div>

      <div class="box">
        <h2 class="title is-4 is-size-5-mobile"> <!-- Alterado para is-size-5-mobile -->
          Nosso Compromisso
        </h2>
        <p>Na SenSwitch, acreditamos que o monitoramento inteligente é a chave para o sucesso operacional. Comprometemo-nos a desenvolver soluções avançadas que não apenas atendam, mas superem as expectativas de nossos clientes. Nosso compromisso é proporcionar um ambiente de gerenciamento de sensores que seja intuitivo, confiável e eficiente, promovendo a excelência nas operações empresariais.</p>
      </div>

      <div class="box">
        <h2 class="title is-4 is-size-5-mobile"> <!-- Alterado para is-size-5-mobile -->
          Por Que SenSwitch?
        </h2>
        <p>Somos mais do que uma solução de gerenciamento de sensores; somos seu parceiro confiável na busca pela excelência operacional. A SenSwitch destaca-se por oferecer uma abordagem abrangente e eficiente, priorizando a segurança, a simplicidade de uso e a personalização para cada cliente. Escolher a SenSwitch significa contar com uma equipe especializada comprometida em impulsionar o desempenho de sua empresa por meio do monitoramento inteligente de sensores.</p>
      </div>
    </div>
  </section>

  <% unless user_signed_in? %>
    <div class="columns is-centered is-vcentered">
      <div class="column is-half">
        <div class="buttons is-centered is-vcentered">
          <%= link_to "Entrar", new_user_session_path, class: "button is-link is-fullwidth is-large is-fullwidth-mobile" %>
          <%= link_to "Registrar", new_user_registration_path, class: "button is-light is-fullwidth is-large is-fullwidth-mobile mb-2" %>
        </div>
      </div>
    </div>
  <% end %>
</body>
</html>

app/views/layouts/_lognotification.html.erb
<style>
  .non-clickable {
    pointer-events: none;
  }
</style>

<script>
document.addEventListener('DOMContentLoaded', () => {
  (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
    const $notification = $delete.parentNode;

    $delete.addEventListener('click', () => {
      $notification.parentNode.removeChild($notification);
    });
    $(document).on('click', '#closeBtn', function () {
    $("#infoPanel").html('');
    infoPanelOpen = false;
  });
  });
});
</script>


<% if flash[:notice] %>
              <div class="notification is-success mb-0 is-unselectable non-clickable" id="logNtf" role="alert" style="margin-top: 48px;">
                <%= flash[:notice] %>
                <button class="delete button is-dark" id="closeBtn" aria-label="Close"></button>
              </div>
            <% end %>
            <% if flash[:alert] %>
              <div class="notification is-warning mb-0 is-unselectable non-clickable" id="logNtf" role="alert">
                <%= flash[:alert] %>
                <button class="delete button is-dark" id="closeBtn" aria-label="Close"></button>
              </div>
<% end %>

app/views/layouts/_monitor.html.erb
<!-- app/views/pages/_monitor.html.erb -->

<style>
  .non-clickable {
    pointer-events: none;
  }
</style>

<div class="container is-mobile">
  <div class="notification is-info is-unselectable non-clickable" id="updateTimeInfo"></div>
  <div class="columns is-multiline is-clickable" id="sensorColumns">
    <!-- Colunas dinâmicas serão adicionadas aqui -->
  </div>
</div>



<div class="message " id="infoPanel">
    
  <!-- Conteúdo da área de informações do sensor -->
  
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<%= javascript_include_tag 'monitor' %>
<script>
document.addEventListener('DOMContentLoaded', () => {
  (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
    const $notification = $delete.parentNode;

    $delete.addEventListener('click', () => {
      $notification.parentNode.removeChild($notification);
    });
    $(document).on('click', '#closeBtn', function () {
    $("#infoPanel").html('');
    infoPanelOpen = false;
  });
  });
});
</script>

app/views/layouts/_navbar.html.erb
<%= javascript_include_tag 'navbar' %>
<nav class="navbar" role="navigation" aria-label="main navigation">

  <div class="navbar-brand">
    <%= link_to(root_path, class: "navbar-item", "data-turbo": false) do %>
      <%= image_tag("logo.png", alt: "Logo SenSwitch", class: "logo-image") %>
      <h2 class = "title is-6">SenSwitch</h2>
    <% end %>

    
    <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  
  <div id="navMenu" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Json", refresh_data_path, class: "navbar-item" %>
      
      <%= link_to "Monitor", monitor_path, class: "navbar-item" %>
      <%= link_to "Sobre", sobre_path, class: "navbar-item" %>
      

    </div>
    <div class="navbar-end" >
      <div class="navbar-item">
        <div class="buttons">
            <% if current_user %>
              <%= button_to "Sair", destroy_user_session_path, method: :delete, class: "button is-light navbar-item" %>
              <%= link_to "Editar Conta", edit_user_registration_path, class: "button is-link navbar-item" %>
            <% else %>
              <%= link_to "Registrar", new_user_registration_path, class: "button is-light navbar-item" %>
              <%= link_to "Entrar", new_user_session_path, class: "button is-link navbar-item" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>

    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='pt-BR'>
<meta charset='UTF-8'>
  <head>
    <title>SenSwitch - Soluções Inteligentes em Gerenciamento de Sensores</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('logo.png') %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    </%= javascript_importmap_tags %>

      
  </head>

  <body>
      <main>
    <% if user_signed_in? %> <!-- Verifica se o usuário está autenticado com Devise -->
  
    <%= render 'layouts/navbar'%>
    <%end%>
        <!--
        <div class =" container is-mobile" style="margin-top: -24px;">
          <%= render 'layouts/lognotification'%>
          <br>
        </div>
         -->
        <%= yield %>
        
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<!-- app/views/pages/home.html.erb -->
<!DOCTYPE html >
<html lang='pt-BR'>
<head>
  <title>Sua Página</title>
  <!-- Adicione os scripts e estilos necessários aqui -->
<% if user_signed_in? %> <!-- Verifica se o usuário está autenticado com Devise -->
  
  <%= render 'layouts/monitor'%>
<% else %>
  <%= render 'layouts/about'%>
  <div class="container is-widescreen">  
    <div class="notification is-warning">
      <p>Você precisa estar logado para acessar o monitoramento de sensores.</p>
      
    </div>
    <progress class="progress is-small is-primary" max="50">10%</progress>
    <br>
  </div>
<% end %>

app/views/pages/monitor.html.erb
<!-- app/views/pages/home.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Monitor</title>
  <!-- Adicione os scripts e estilos necessários aqui -->
<% if user_signed_in? %> <!-- Verifica se o usuário está autenticado com Devise -->
  <div class = " box title is-2">
    <h2></h2>   
  </div>
  <%= render 'layouts/monitor'%>
<% else %>
  <div class="container is-widescreen">  
    <div class="notification is-warning">
      <p>Você precisa estar logado para acessar esta página.</p>
    </div>
  </div>
<% end %>

app/views/pages/sobre.html.erb
<%= render 'layouts/about'%>

app/views/pages/test.html.erb
<h1>Pages#sobre</h1>
<p>Find me in app/views/pages/teste.html.erb</p>


<%= link_to "Home", root_path, "data-turbo": false, class:"button is-danger"%>

<button onclick="mostrarNotificacao()" class="button is-link">Mostrar Notificação</button>
<script>
function mostrarNotificacao() {
  // Verifica se o navegador suporta notificações
  if ('Notification' in window) {
    // Solicita permissão para exibir notificações
    Notification.requestPermission().then(function (permission) {
      if (permission === 'granted') {
        // Cria uma nova notificação
        var notificacao = new Notification('⚠Aviso de erro em sensor⚠', {
          body: 'Sensor "Teste" não esta funcionando corretamente',
          icon: 'app/assets/images/1.png' // Opcional: caminho para um ícone personalizado
        });

        // Adiciona um evento de clique na notificação
        notificacao.onclick = function () {
          //alert('Notificação clicada!');
          window.location.href = '/monitor';
        };
      }
    });
  }
}
</script>